- name: Disallow SSH password authentication
  hosts: all
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication no"
    state=present
    validate: sshd -t -f %s
  notify:
    - restart sshd